### ISSUE TITLE
Support Newer Node.js Versions

### ISSUE THREAD

**Issue by bosconian-dynamics** [getdnsapi/getdns-node#35]
I would love to employ this library, but am unable to due to the Node.js engine constraints. The most recent version of Node.js currently supported is 10 which reaches end of life next month.

Are there any plans to update `getdns-node` to support newer engines?

**Comment by joelpurra** [comment]
@bosconian-dynamics: sure, I have upgraded to the current Node.js LTS versions v10, v12, v14. Released as [getdns-node](https://www.npmjs.com/package/getdns) v3.0.0.

Note that v15 is not LTS and v16 is not yet released, but manual testing seem to show that they work as well as the other versions. (This means that they all have segfault problems and are crash-prone during tests.)

**Comment by bosconian-dynamics** [comment]
> @bosconian-dynamics: sure, I have upgraded to the current Node.js LTS versions v10, v12, v14. Released as [getdns v3.0.0 on `npm`](https://www.npmjs.com/package/getdns).
> 
> Note that v15 is not LTS and v16 is not yet released, but manual testing seem to show that they work as well as the other versions. (This means that they all have segfault problems and are crash-prone during tests.)

Awesome! Thank you very much 😁

**Comment by joelpurra** [comment]
As a follow-up, I just upgraded to the current Node.js LTS versions v12, v14, v16. Released as [getdns v4.0.0 on npm](https://www.npmjs.com/package/getdns).
