### ISSUE TITLE
Update to works with iojs 3.x

### ISSUE THREAD

**Issue by Dexus** [getdnsapi/getdns-node#4]
* nan need to update to 2.x
* compiler need to be g++-4.8 and above for new V8

**Comment by ngoyal** [comment]
Thanks for the heads up - nan 2.x is quite the change.  I'm working on this as time permits.  PRs most definitely welcome!

**Comment by Dexus** [comment]
If I knew more of C ++ I would pull a Request erstellen.Leider I'm not so well versed.

**Comment by joelpurra** [comment]
@ngoyal, @Dexus: could you guys have a look at #6 and see if it works for you?

**Comment by joelpurra** [comment]
With tests passing locally since #6 and on Travis since #12, I'm closing this.
