### ISSUE TITLE
Compilation error with latest getdns

### ISSUE THREAD

**Issue by saghul** [getdnsapi/getdns-node#8]
Hi there!

I installed the latest getdns with Homebew and compilation fails because a constant cannot be found:

```
  CXX(target) Release/obj.target/getdns/src/GNConstants.o
../src/GNConstants.cpp:87:53: error: use of undeclared identifier 'GETDNS_APPEND_NAME_TO_SINGLE_LABEL_FIRST'
    SetConstant("APPEND_NAME_TO_SINGLE_LABEL_FIRST",GETDNS_APPEND_NAME_TO_SINGLE_LABEL_FIRST,exports);
                                                    ^
```

**Comment by joelpurra** [comment]
@saghul: [Homebrew's getdns formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/getdns.rb) is still targeting getdns v0.9.0. The current `master` here in `getdns-node` targets the getdns v1.0.0 prereleases (such as [`v1.0.0b2`](https://github.com/getdnsapi/getdns/tree/v1.0.0b2)). If `brew install getdns --HEAD` would have worked I would have recommended that; alas, it does not (needs to be looked at).

For a local (unofficial) Mac setup I'm using my own [getdns-developer-support](https://github.com/joelpurra/getdns-developer-support) scripts. YMMV, but do let me know if that's of any help!

**Comment by saghul** [comment]
Thanks for the heads up, installing with `--HEAD` does indeed fail 😢

**Comment by joelpurra** [comment]
@saghul: opened an issue upstream: https://github.com/getdnsapi/getdns/issues/209 -- would also like to see support for `brew install --devel getdns`.

**Comment by joelpurra** [comment]
@saghul: see pull request https://github.com/Homebrew/homebrew-core/pull/11578 for `brew install getdns` with `v1.0.0`, `--devel` for `v1.1.0-rc1` (currently failing with brew) and `--HEAD` for getdns' `develop` branch (currently failing with brew) and info in https://github.com/getdnsapi/getdns/issues/209.

**Comment by joelpurra** [comment]
Homebrew has now accepted the getdns v1.0.0 pull request; users should be installing/upgrading to it automatically. This should make it easier for users and devs to get started with getdns-node.

Closing this issue. Thanks!
